### PR TITLE
Address ambiguity around patent grant

### PR DESCRIPTION
**Pull request by tieguy**
I'm wrestling with the patent grant here; the "or" is ambiguous. Two possible constructions:
- "you may do everything with ... any patent claim that I license": not consistent with other licenses as it doesn't tie the usage to this particular piece of software. (Though perhaps this is intentional, as the utility of this tie has always been somewhat debatable in the context of permissive licenses.)
- "you may do everything with this software that would otherwise infringe ... any patent claim I can license that you would infringe by using this software" - I think this is probably what you meant, but the repeated use of "infringe" makes me somewhat uncertain?

The pull request fixes the ambiguity with brute force. It does not fix the awkward dual "infringe"; I'd like something more parallel but I don't see an obvious change that would fix without running into complexity around the subtly but importantly different definitions of what is being licensed.

### CODE REVIEW

**Comment by tieguy** [comment]
(Realizing that this should probably have been against Parity, not Posterity - sorry!)

**Comment by kemitchell** [comment]
@tieguy leave it here. I am grateful. Let me wrangle issues and repos.

**Comment by kemitchell** [comment]
I want to read this at least twice before I respond to your main point. But on the smaller issue of "infringe ... infringe", predecessor drafts had something like:

> If you follow the rules below, you may do everything with this software that would otherwise infringe my copyright in it or any patent claim I can license that reads on this software as of my latest contribution.

The patentspeak "reads on" understandably confused hackers.

Do you see improvement, at least on the awkwardness front, in this?

> If you follow the rules below, you may do everything with this software that would otherwise infringe my copyright in it or any patent claim I can license that covers this software as of my latest contribution.

**Comment by tieguy** [comment]
Yes, infringe >> reads on given those goals.

**Comment by kemitchell** [comment]
@tieguy, thanks again for this.

It was _not_ my intention to grant total patent licenses unmoored from the software. I'm not sure that reading is high-probability, but I agree it's potentially very high-cost.

Here is where I am at the moment:

f7b7e9c8046d535953e7d365d9f7988ac429e61e

> If you follow the rules below, you may do everything with this software that would otherwise infringe my copyright in it, any patent claim I can license that covers this software as of my latest contribution, or both.

I think your use of enumeration is very sharp instinct. It's a structural concern, and we want to keep things lean and tight. But I think that particular structural tool would be pretty alienating. I was very careful to number my rules with `1.`, rather than `(1)`, for just that reason.

My first attempt at a fix here was with "either". That's a nice syntactic marker, and avoids the technicality of "or both", but there's debate on whether it implies exclusive disjunction. That will get _both_ the law people and the coder people riled up. Which nobody wants.

You mentioned that permissive licenses make the scope of existing patent language a bit fuzzy. But as you pointed out, the language we're discussing doesn't just appear in permissive licenses. :stuck_out_tongue_winking_eye: If this leads to a better place, I will backport to other members of the license family.

**Comment by kemitchell** [comment]
We could also go ahead and use "either", too:

> If you follow the rules below, you may do everything with this software that would otherwise infringe <ins>either</ins> my copyright in it, any patent claim I can license that covers this software as of my latest contribution, or both.

"Either" does not appear elsewhere in any of the licenses in the family.

**Pull request closed without merging**
